// Catálogo oficial de fontes de cotações e mercado da TPEC-IA.
// Gerado a partir da lista aprovada em 30/07/2026.
// kind = "rag"      -> material estável (metodologia, relatórios, estudos) que vai para a base de conhecimento.
// kind = "dynamic"  -> dado que muda (cotação, câmbio, futuros, exportação, abate, diesel) e precisa
//                      ser coletado por API/CSV/planilha e gravado em `market_quotes`.
// ATENÇÃO JURÍDICA: link disponível != autorização para copiar/raspar/republicar.
// Respeite `licenseNote` de cada fonte (ex.: CEPEA usa CC BY-NC 4.0 em vários indicadores).

export interface MarketSourceSeed {
  code: string;
  name: string;
  org: string;
  category: string;
  url: string;
  kind: "rag" | "dynamic";
  phase: number;
  region: string;
  ingestMethod: string;
  licenseNote: string;
}

export const MARKET_SOURCES: MarketSourceSeed[] = [
  {"code": "cepea_portal", "name": "Portal CEPEA/ESALQ", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0 em vários indicadores - uso comercial requer autorização"},
  {"code": "cepea_boi_gordo", "name": "Indicador do boi gordo", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/boi-gordo.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_bezerro", "name": "Indicador do bezerro", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/bezerro.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_milho", "name": "Indicador do milho", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/milho.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_soja", "name": "Indicador da soja", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/soja.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_leite", "name": "Leite ao produtor e leite spot", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/leite.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_lacteos", "name": "Derivados lácteos no atacado", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/leite-derivados-atacado.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_captacao_leite", "name": "Índice de captação de leite", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/leite-indice-de-captacao.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_frango", "name": "Preços do frango", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/frango.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_suino", "name": "Suíno vivo e carcaça", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/suino.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_ovos", "name": "Preços dos ovos", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/ovos.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_ovinos", "name": "Preços de ovinos", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/ovinos.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_tilapia", "name": "Preços de tilápia", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/indicador/tilapia.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_insumos", "name": "Preços de insumos pecuários", "org": "CEPEA", "category": "custos", "url": "https://cepea.org.br/br/insumos-pecuarios.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "csv", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_series", "name": "Séries históricas CEPEA", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/consultas-ao-banco-de-dados-do-site.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_widget", "name": "Widget oficial de cotações", "org": "CEPEA", "category": "cotacoes", "url": "https://www.cepea.esalq.usp.br/br/widget.aspx", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Widget oficial - uso conforme termos CEPEA"},
  {"code": "cepea_rel_pecuarios", "name": "Relatórios pecuários", "org": "CEPEA", "category": "relatorios", "url": "https://cepea.org.br/br/categoria/relatorios-pecuarios.aspx", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_rel_agricolas", "name": "Relatórios agrícolas", "org": "CEPEA", "category": "relatorios", "url": "https://cepea.org.br/br/categoria/relatorios-agricolas.aspx", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "b3_bgi", "name": "Futuro de boi gordo (BGI)", "org": "B3", "category": "futuros", "url": "https://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/commodities/ficha-do-produto-8AA8D0CC9DBDCB54019DC0DEE4755111.htm", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3 - verificar termos de uso"},
  {"code": "b3_ccm", "name": "Futuro de milho (CCM)", "org": "B3", "category": "futuros", "url": "https://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/commodities/ficha-do-produto-8AE490CA6D41D4C7016D45F3CB0A38F0.htm", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3 - verificar termos de uso"},
  {"code": "b3_ifboi", "name": "Índice Futuro de Boi Gordo (IFBOI)", "org": "B3", "category": "futuros", "url": "https://www.b3.com.br/pt_br/market-data-e-indices/indices/indices-de-segmentos-e-setoriais/indice-futuro-de-boi-gordo-b3-ifboi-b3.htm", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3"},
  {"code": "b3_ifmilho", "name": "Índice Futuro de Milho (IFMILHO)", "org": "B3", "category": "futuros", "url": "https://www.b3.com.br/pt_br/market-data-e-indices/indices/indices-de-segmentos-e-setoriais/indice-futuro-de-milho-b3-ifmilho-b3.htm", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3"},
  {"code": "b3_horarios", "name": "Horários de negociação de commodities", "org": "B3", "category": "metodologia", "url": "https://www.b3.com.br/pt_br/solucoes/plataformas/puma-trading-system/para-participantes-e-traders/horario-de-negociacao/derivativos/commodities/", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3"},
  {"code": "b3_edu_boi", "name": "Material educativo futuro de boi gordo", "org": "B3", "category": "metodologia", "url": "https://edu.b3.com.br/w/futuro-boi-gordo", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3"},
  {"code": "conab_precos", "name": "Preços agropecuários atuais", "org": "Conab", "category": "cotacoes", "url": "https://portaldeinformacoes.conab.gov.br/precos-agropecuarios.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_precos_hist", "name": "Séries históricas de preços", "org": "Conab", "category": "cotacoes", "url": "https://portaldeinformacoes.conab.gov.br/precos-agropecuarios-serie-historica.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_downloads", "name": "Arquivos para download (preços, frete, safras)", "org": "Conab", "category": "cotacoes", "url": "https://portaldeinformacoes.conab.gov.br/download-arquivos.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_oferta_demanda", "name": "Oferta e demanda agropecuária", "org": "Conab", "category": "oferta_demanda", "url": "https://portaldeinformacoes.conab.gov.br/oferta-e-demanda.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_precos_minimos", "name": "Preços mínimos oficiais", "org": "Conab", "category": "cotacoes", "url": "https://portaldeinformacoes.conab.gov.br/precos-minimos", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_safra_hist", "name": "Série histórica de safras de grãos", "org": "Conab", "category": "oferta_demanda", "url": "https://portaldeinformacoes.conab.gov.br/safra-serie-historica-graos.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_safra_estim", "name": "Estimativa de evolução da safra", "org": "Conab", "category": "oferta_demanda", "url": "https://portaldeinformacoes.conab.gov.br/safra-estimativa-de-evolucao-graos.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "conab_custos", "name": "Custos de produção", "org": "Conab", "category": "custos", "url": "https://portaldeinformacoes.conab.gov.br/custos-de-producao.html", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "imea_indicadores", "name": "Indicadores de Mato Grosso", "org": "IMEA", "category": "cotacoes", "url": "https://www.imea.com.br/imea-site/indicadores", "kind": "dynamic", "phase": 1, "region": "MT", "ingestMethod": "csv", "licenseNote": "Verificar termos IMEA"},
  {"code": "iea_sp_banco", "name": "Banco de dados de preços agropecuários SP", "org": "IEA/SP", "category": "cotacoes", "url": "https://iea.agricultura.sp.gov.br/out/Bancodedados.php", "kind": "dynamic", "phase": 1, "region": "SP", "ingestMethod": "csv", "licenseNote": "Dado público estadual"},
  {"code": "iea_sp_metodologia", "name": "Metodologia dos preços recebidos", "org": "IEA/SP", "category": "metodologia", "url": "https://iea.agricultura.sp.gov.br/out/metodologia.html", "kind": "rag", "phase": 1, "region": "SP", "ingestMethod": "manual", "licenseNote": "Dado público estadual"},
  {"code": "epagri_mercado", "name": "Preços agrícolas de Santa Catarina", "org": "Epagri/Cepa", "category": "cotacoes", "url": "https://cepa.epagri.sc.gov.br/index.php/mercado-agricola/", "kind": "dynamic", "phase": 1, "region": "SC", "ingestMethod": "csv", "licenseNote": "Dado público estadual"},
  {"code": "epagri_boletins", "name": "Boletins e estudos agropecuários", "org": "Epagri/Cepa", "category": "relatorios", "url": "https://cepa.epagri.sc.gov.br/", "kind": "rag", "phase": 2, "region": "SC", "ingestMethod": "manual", "licenseNote": "Dado público estadual"},
  {"code": "scot_cotacoes", "name": "Cotações de boi gordo e reposição", "org": "Scot Consultoria", "category": "cotacoes", "url": "https://www.scotconsultoria.com.br/cotacoes/", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo privado - requer autorização"},
  {"code": "noticias_agricolas", "name": "Central de cotações", "org": "Notícias Agrícolas", "category": "cotacoes", "url": "https://www.noticiasagricolas.com.br/cotacoes/", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo privado - requer autorização"},
  {"code": "noticias_agricolas_b3", "name": "Boi gordo na B3", "org": "Notícias Agrícolas", "category": "futuros", "url": "https://www.noticiasagricolas.com.br/cotacoes/boi-gordo/boi-gordo-b3-prego-regular", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo privado - requer autorização"},
  {"code": "agrolink_cotacoes", "name": "Cotações regionais", "org": "Agrolink", "category": "cotacoes", "url": "https://www.agrolink.com.br/cotacoes", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo privado - requer autorização"},
  {"code": "agrostat", "name": "Exportações e importações do agronegócio", "org": "MAPA", "category": "exportacoes", "url": "https://sistemasweb.agricultura.gov.br/pages/AGROSTAT.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "mapa_indicadores", "name": "Portal de indicadores do MAPA", "org": "MAPA", "category": "exportacoes", "url": "https://indicadores.agro.gov.br/", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "comexstat_home", "name": "Comex Stat", "org": "MDIC", "category": "exportacoes", "url": "https://comexstat.mdic.gov.br/pt/home", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "comexstat_geral", "name": "Comex Stat - consulta geral", "org": "MDIC", "category": "exportacoes", "url": "https://comexstat.mdic.gov.br/pt/geral", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "comexstat_municipio", "name": "Comex Stat - por município", "org": "MDIC", "category": "exportacoes", "url": "https://comexstat.mdic.gov.br/pt/municipio", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "comexstat_api", "name": "API oficial do Comex Stat", "org": "MDIC", "category": "exportacoes", "url": "https://api-comexstat.mdic.gov.br/docs", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "comexstat_bruta", "name": "Base de dados bruta Comex Stat", "org": "MDIC", "category": "exportacoes", "url": "https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/estatisticas/base-de-dados-bruta", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "abiec_exportacoes", "name": "Estatísticas de exportação de carne bovina", "org": "ABIEC", "category": "exportacoes", "url": "https://abiec.com.br/exportacoes/", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo de associação - verificar termos"},
  {"code": "abiec_beef_report_pag", "name": "Beef Report 2025", "org": "ABIEC", "category": "relatorios", "url": "https://abiec.com.br/publicacoes/beef-report-2025-perfil-da-pecuaria-no-brasil/", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo de associação"},
  {"code": "abiec_beef_report_pdf", "name": "Beef Report 2025 (PDF)", "org": "ABIEC", "category": "relatorios", "url": "https://abiec.com.br/wp-content/uploads/2025/06/Beef-Report-2025.pdf", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo de associação"},
  {"code": "ibge_ppm", "name": "Pesquisa da Pecuária Municipal", "org": "IBGE", "category": "rebanho", "url": "https://www.ibge.gov.br/estatisticas/economicas/agricultura-e-pecuaria/9107-producao-da-pecuaria-municipal.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "ibge_abate", "name": "Pesquisa Trimestral do Abate", "org": "IBGE", "category": "abates", "url": "https://www.ibge.gov.br/estatisticas/economicas/agricultura-e-pecuaria/9203-pesquisas-trimestrais-do-abate-de-animais.html", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "sidra_abate", "name": "Tabelas SIDRA do abate", "org": "IBGE", "category": "abates", "url": "https://sidra.ibge.gov.br/pesquisa/abate/tabelas/", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "ibge_leite", "name": "Pesquisa Trimestral do Leite", "org": "IBGE", "category": "rebanho", "url": "https://www.ibge.gov.br/estatisticas/economicas/agricultura-e-pecuaria/9209-pesquisa-trimestral-do-leite.html", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "ibge_ovos", "name": "Pesquisa Trimestral de Ovos", "org": "IBGE", "category": "rebanho", "url": "https://www.ibge.gov.br/estatisticas/economicas/agricultura-e-pecuaria/9216-pesquisa-trimestral-da-producao-de-ovos-de-galinha.html", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "ibge_couro", "name": "Pesquisa Trimestral do Couro", "org": "IBGE", "category": "rebanho", "url": "https://www.ibge.gov.br/estatisticas/economicas/agricultura-e-pecuaria/9214-pesquisa-trimestral-do-couro.html", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "cepea_indices_export", "name": "Índices de exportação do agronegócio", "org": "CEPEA", "category": "exportacoes", "url": "https://cepea.org.br/br/indicador/serie-indices-de-exportacao-do-agronegocio.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "csv", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_pib_agro", "name": "PIB do agronegócio", "org": "CEPEA/CNA", "category": "relatorios", "url": "https://cepea.org.br/br/pib-do-agronegocio-brasileiro.aspx", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_ippa", "name": "IPPA - índice de preços ao produtor", "org": "CEPEA", "category": "cotacoes", "url": "https://cepea.org.br/br/ippa.aspx", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "csv", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cna_campo_futuro", "name": "Projeto Campo Futuro", "org": "CNA", "category": "custos", "url": "https://cnabrasil.org.br/projetos-e-programas/campo-futuro", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo CNA"},
  {"code": "cna_metodologia", "name": "Metodologia do Campo Futuro (PDF)", "org": "CNA", "category": "metodologia", "url": "https://cnabrasil.org.br/storage/arquivos/dtec.Metodologia.Campo.Futuro.2022.04.nov.2021.pdf", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo CNA"},
  {"code": "cna_custos_paineis", "name": "Custos de pecuária de leite e corte", "org": "CNA", "category": "custos", "url": "https://cnabrasil.org.br/noticias/campo-futuro-realiza-paineis-de-custos-de-producao-de-pecuaria-de-leite-e-de-corte", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo CNA"},
  {"code": "cna_ebook_leite", "name": "Ebook Campo Futuro - pecuária de leite", "org": "CNA", "category": "custos", "url": "https://cnabrasil.org.br/storage/arquivos/Ebook-Campo-Futuro-2022-Pec.-Leite.pdf", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo CNA"},
  {"code": "embrapa_custobov", "name": "CustoBov - planilha de custos", "org": "Embrapa", "category": "custos", "url": "https://www.embrapa.br/busca-de-solucoes-tecnologicas/-/produto-servico/4049/custobov---planilha-de-controle-de-custos-e-margens-da-bovinocultura-de-corte", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "embrapa_custobov_pub", "name": "Publicação sobre o CustoBov", "org": "Embrapa", "category": "custos", "url": "https://www.embrapa.br/busca-de-publicacoes/-/publicacao/1082372/custobov-aplicativo-para-controle-de-custos-e-margens-da-bovinocultura-de-corte", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "embrapa_custos_corte", "name": "Custos de produção na pecuária de corte", "org": "Embrapa", "category": "custos", "url": "https://www.infoteca.cnptia.embrapa.br/infoteca/bitstream/doc/326855/1/COT104.pdf", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "embrapa_custos_pantanal", "name": "Custo de produção no Pantanal", "org": "Embrapa", "category": "custos", "url": "https://www.infoteca.cnptia.embrapa.br/infoteca/bitstream/doc/1166855/1/Custo-de-producao-da-pecuaria-de-corte-no-Pantanal-CT126-Abreu.pdf", "kind": "rag", "phase": 2, "region": "MS", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "embrapa_custo_leite", "name": "Planilha de custo de produção de leite", "org": "Embrapa", "category": "custos", "url": "https://www.infoteca.cnptia.embrapa.br/bitstream/doc/45571/4/PROCICircT32OT2002.00003.PDF", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "cepea_metod_insumos", "name": "Metodologia do índice de insumos pecuários", "org": "CEPEA/CNA", "category": "metodologia", "url": "https://www.cepea.org.br/upload/kceditor/files/metodologiacna.pdf", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_gestao", "name": "Gestão do negócio agropecuário", "org": "CEPEA", "category": "custos", "url": "https://cepea.org.br/br/gestao-do-negocio-agropecuario.aspx", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "anp_precos_semanas", "name": "Preços de combustíveis - últimas semanas", "org": "ANP", "category": "diesel", "url": "https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/levantamento-de-precos-de-combustiveis-ultimas-semanas-pesquisadas", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "anp_serie_hist", "name": "Série histórica de preços de combustíveis", "org": "ANP", "category": "diesel", "url": "https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/serie-historica-do-levantamento-de-precos", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "csv", "licenseNote": "Dado público governamental"},
  {"code": "anp_painel", "name": "Painel dinâmico de preços", "org": "ANP", "category": "diesel", "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/paineis-dinamicos-da-anp/painel-dinamico-de-precos-de-combustiveis-e-derivados-do-petroleo", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Dado público governamental"},
  {"code": "antt_frete", "name": "Pisos mínimos de frete", "org": "ANTT", "category": "frete", "url": "https://www.gov.br/antt/pt-br/assuntos/cargas/politica-nacional-de-pisos-minimos-de-frete", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Dado público governamental"},
  {"code": "bcb_sgs", "name": "Sistema Gerenciador de Séries Temporais", "org": "Banco Central", "category": "cambio", "url": "https://www3.bcb.gov.br/sgspub/", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "bcb_dados_abertos", "name": "Dados abertos do Banco Central", "org": "Banco Central", "category": "cambio", "url": "https://dadosabertos.bcb.gov.br/", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "bcb_selic", "name": "Série da Selic", "org": "Banco Central", "category": "cambio", "url": "https://dadosabertos.bcb.gov.br/dataset/11-taxa-de-juros---selic/resource/b73edc07-bbac-430c-a2cb-b1639e605fa8", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "bcb_ptax", "name": "Cotações oficiais de moedas (PTAX)", "org": "Banco Central", "category": "cambio", "url": "https://www.bcb.gov.br/estabilidadefinanceira/cotacoestodas", "kind": "dynamic", "phase": 1, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "bcb_focus", "name": "Relatório Focus", "org": "Banco Central", "category": "cambio", "url": "https://www.bcb.gov.br/publicacoes/focus", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "api", "licenseNote": "Dado público governamental"},
  {"code": "usda_psd", "name": "USDA PSD Online", "org": "USDA", "category": "internacional", "url": "https://apps.fas.usda.gov/psdonline/", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "api", "licenseNote": "Dado público - domínio governamental EUA"},
  {"code": "usda_fas_data", "name": "USDA FAS - dados e análises", "org": "USDA", "category": "internacional", "url": "https://www.fas.usda.gov/data", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "api", "licenseNote": "Dado público EUA"},
  {"code": "usda_livestock_pdf", "name": "Livestock and Poultry: World Markets and Trade", "org": "USDA", "category": "relatorios", "url": "https://apps.fas.usda.gov/psdonline/circulars/livestock_poultry.pdf", "kind": "rag", "phase": 2, "region": "INT", "ingestMethod": "manual", "licenseNote": "Dado público EUA"},
  {"code": "usda_brasil_2026", "name": "Relatório 2026 sobre pecuária no Brasil", "org": "USDA", "category": "relatorios", "url": "https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=Livestock+and+Products+Semi-annual_Brasilia_Brazil_BR2026-0010.pdf", "kind": "rag", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Dado público EUA"},
  {"code": "usda_market_news", "name": "USDA Market News - dados históricos", "org": "USDA", "category": "internacional", "url": "https://mpr.datamart.ams.usda.gov/", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "api", "licenseNote": "Dado público EUA"},
  {"code": "usda_mymarketnews", "name": "My Market News e API", "org": "USDA", "category": "internacional", "url": "https://mymarketnews.ams.usda.gov/", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "api", "licenseNote": "Dado público EUA - requer chave"},
  {"code": "usda_marsapi", "name": "API de relatórios USDA Market News", "org": "USDA", "category": "internacional", "url": "https://marsapi.ams.usda.gov/services/v1.1/reports/", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "api", "licenseNote": "Dado público EUA - requer chave"},
  {"code": "fao_meat_index", "name": "FAO Meat Price Index", "org": "FAO", "category": "internacional", "url": "https://www.fao.org/markets-and-trade/commodities-overview/basic-foods/fao-meat-price-index/en", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "csv", "licenseNote": "FAO - verificar termos"},
  {"code": "fao_food_index", "name": "FAO Food Price Index", "org": "FAO", "category": "internacional", "url": "https://www.fao.org/worldfoodsituation/FoodPricesIndex/en/", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "csv", "licenseNote": "FAO - verificar termos"},
  {"code": "fao_planilha", "name": "Planilha mensal dos índices FAO", "org": "FAO", "category": "internacional", "url": "https://www.fao.org/fileadmin/templates/worldfood/Reports_and_docs/Food_price_indices_data_may629.xls", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "csv", "licenseNote": "FAO - verificar termos"},
  {"code": "worldbank_pinksheet", "name": "Commodity Markets e Pink Sheet", "org": "Banco Mundial", "category": "internacional", "url": "https://www.worldbank.org/en/research/commodity-markets", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "csv", "licenseNote": "CC BY 4.0 (verificar)"},
  {"code": "cme_live_cattle", "name": "CME - futuros de boi vivo", "org": "CME Group", "category": "internacional", "url": "https://www.cmegroup.com/markets/agriculture/livestock/live-cattle.quotes.html", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "manual", "licenseNote": "Conteúdo privado - verificar termos"},
  {"code": "cme_corn", "name": "CME - futuros de milho", "org": "CME Group", "category": "internacional", "url": "https://www.cmegroup.com/markets/agriculture/grains/corn.quotes.html", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "manual", "licenseNote": "Conteúdo privado"},
  {"code": "cme_soybean", "name": "CME - futuros de soja", "org": "CME Group", "category": "internacional", "url": "https://www.cmegroup.com/markets/agriculture/oilseeds/soybean.quotes.html", "kind": "dynamic", "phase": 2, "region": "INT", "ingestMethod": "manual", "licenseNote": "Conteúdo privado"},
  {"code": "cme_fob_santos", "name": "CME - soja FOB Santos", "org": "CME Group", "category": "internacional", "url": "https://www.cmegroup.com/markets/agriculture/oilseeds/fob-santos-soybeans-financially-settled-platts.quotes.html", "kind": "dynamic", "phase": 2, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo privado"},
  {"code": "cepea_metod_boi", "name": "Metodologia do Indicador do Boi Gordo", "org": "CEPEA", "category": "metodologia", "url": "https://www.cepea.esalq.usp.br/upload/kceditor/files/boigordoMETODOL_Ind_BOI_GORDO_Cepea.pdf", "kind": "rag", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "cepea_metod_milho", "name": "Metodologia do Indicador do Milho", "org": "CEPEA", "category": "metodologia", "url": "https://www.cepea.esalq.usp.br/upload/kceditor/files/Metodologia%20Milho.pdf", "kind": "rag", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "CC BY-NC 4.0"},
  {"code": "b3_espec_boi", "name": "Especificação do contrato futuro de boi gordo", "org": "B3", "category": "metodologia", "url": "https://www.b3.com.br/lumis/portal/file/fileDownload.jsp?fileId=8AA8D097531AC0FD0153573216E600D6", "kind": "rag", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3"},
  {"code": "b3_espec_milho", "name": "Especificação do contrato futuro de milho", "org": "B3", "category": "metodologia", "url": "https://www.b3.com.br/lumis/portal/file/fileDownload.jsp?fileId=8A828D2951C9C37701520D830FC15037", "kind": "rag", "phase": 1, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo B3"},
  {"code": "embrapa_hedge", "name": "Efetividade e razão ótima de hedge do boi gordo", "org": "Embrapa", "category": "relatorios", "url": "https://www.alice.cnptia.embrapa.br/alice/bitstream/doc/897448/1/30.pdf", "kind": "rag", "phase": 3, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "embrapa_diagnostico", "name": "Diagnóstico estratégico da cadeia da carne bovina", "org": "Embrapa", "category": "relatorios", "url": "https://www.infoteca.cnptia.embrapa.br/infoteca/bitstream/doc/1148845/1/Diagnostico-estrategico-cadeia-2022.pdf", "kind": "rag", "phase": 3, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "embrapa_cadeia", "name": "Cadeia produtiva da carne bovina: contexto e desafios", "org": "Embrapa", "category": "relatorios", "url": "https://www.infoteca.cnptia.embrapa.br/infoteca/bitstream/doc/1132914/1/DOC-291-Final-em-Alta.pdf", "kind": "rag", "phase": 3, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "iea_risco_boi", "name": "Análise quantitativa do risco de mercado do boi gordo", "org": "IEA/SP", "category": "relatorios", "url": "https://iea.agricultura.sp.gov.br/ftpiea/publicacoes/IE/2016/tec2-1016.pdf", "kind": "rag", "phase": 3, "region": "SP", "ingestMethod": "manual", "licenseNote": "Dado público estadual"},
  {"code": "embrapa_volatilidade", "name": "Previsão e volatilidade do preço de exportação do boi gordo", "org": "Embrapa/RPA", "category": "relatorios", "url": "https://rpa.sede.embrapa.br/RPA/article/download/1970/1463/4327", "kind": "rag", "phase": 3, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo Embrapa"},
  {"code": "sigabov", "name": "Boletim SIGABOV - bovinos e reposição em MS", "org": "Sistema Famasul", "category": "relatorios", "url": "https://portal.sistemafamasul.com.br/sites/default/files/boletimcasapdf/BOLETIM%20SIGABOV%20Ed.%2058%20-%20Abril%202025.pdf", "kind": "rag", "phase": 3, "region": "MS", "ingestMethod": "manual", "licenseNote": "Conteúdo de federação"},
  {"code": "scot_boi_cia", "name": "Informativo Boi & Companhia", "org": "Scot Consultoria", "category": "relatorios", "url": "https://materiais.scotconsultoria.com.br/boi-cia-edicao-especial-2026", "kind": "rag", "phase": 3, "region": "BR", "ingestMethod": "manual", "licenseNote": "Conteúdo privado"},
  {"code": "imea_rel_bovino", "name": "Relatório de mercado da bovinocultura de corte", "org": "IMEA", "category": "relatorios", "url": "https://publicacoes.imea.com.br/relatorio-de-mercado/bs-bovinoculturadecorte/891", "kind": "rag", "phase": 3, "region": "MT", "ingestMethod": "manual", "licenseNote": "Verificar termos IMEA"},
];

export function findSource(code: string): MarketSourceSeed | undefined {
  return MARKET_SOURCES.find((s) => s.code === code);
}
