/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AuthenticatedAdminBaseConhecimentoRouteImport } from './routes/_authenticated/admin.base-conhecimento'
import { Route as AuthenticatedAdminCotacoesRouteImport } from './routes/_authenticated/admin.cotacoes'
import { Route as AuthenticatedAdminIaRouteImport } from './routes/_authenticated/admin.ia'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicChatTestRouteImport } from './routes/api/public/chat-test'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/diag'
import { Route as ApiPublicMarketIngestRouteImport } from './routes/api/public/market-ingest'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBaseConhecimentoRoute =
  AuthenticatedAdminBaseConhecimentoRouteImport.update({
    id: '/admin/base-conhecimento',
    path: '/admin/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCotacoesRoute =
  AuthenticatedAdminCotacoesRouteImport.update({
    id: '/admin/cotacoes',
    path: '/admin/cotacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIaRoute = AuthenticatedAdminIaRouteImport.update({
  id: '/admin/ia',
  path: '/admin/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatTestRoute = ApiPublicChatTestRouteImport.update({
  id: '/api/public/chat-test',
  path: '/api/public/chat-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/diag',
  path: '/api/public/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketIngestRoute = ApiPublicMarketIngestRouteImport.update({
  id: '/api/public/market-ingest',
  path: '/api/public/market-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/base-conhecimento': typeof AuthenticatedAdminBaseConhecimentoRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/chat-test': typeof ApiPublicChatTestRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/market-ingest': typeof ApiPublicMarketIngestRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/base-conhecimento': typeof AuthenticatedAdminBaseConhecimentoRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/admin/ia': typeof AuthenticatedAdminIaRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/chat-test': typeof ApiPublicChatTestRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/market-ingest': typeof ApiPublicMarketIngestRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/_authenticated/admin/base-conhecimento': typeof AuthenticatedAdminBaseConhecimentoRoute
  '/_authenticated/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/_authenticated/admin/ia': typeof AuthenticatedAdminIaRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/chat-test': typeof ApiPublicChatTestRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/market-ingest': typeof ApiPublicMarketIngestRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exclusao-de-dados'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/base-conhecimento'
    | '/admin/cotacoes'
    | '/admin/ia'
    | '/admin/produtos'
    | '/api/public/chat'
    | '/api/public/chat-test'
    | '/api/public/diag'
    | '/api/public/market-ingest'
    | '/api/public/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exclusao-de-dados'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/base-conhecimento'
    | '/admin/cotacoes'
    | '/admin/ia'
    | '/admin/produtos'
    | '/api/public/chat'
    | '/api/public/chat-test'
    | '/api/public/diag'
    | '/api/public/market-ingest'
    | '/api/public/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/exclusao-de-dados'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/_authenticated/admin/base-conhecimento'
    | '/_authenticated/admin/cotacoes'
    | '/_authenticated/admin/ia'
    | '/_authenticated/admin/produtos'
    | '/api/public/chat'
    | '/api/public/chat-test'
    | '/api/public/diag'
    | '/api/public/market-ingest'
    | '/api/public/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicChatTestRoute: typeof ApiPublicChatTestRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
  ApiPublicMarketIngestRoute: typeof ApiPublicMarketIngestRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/base-conhecimento': {
      id: '/_authenticated/admin/base-conhecimento'
      path: '/admin/base-conhecimento'
      fullPath: '/admin/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedAdminBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cotacoes': {
      id: '/_authenticated/admin/cotacoes'
      path: '/admin/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AuthenticatedAdminCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ia': {
      id: '/_authenticated/admin/ia'
      path: '/admin/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AuthenticatedAdminIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-test': {
      id: '/api/public/chat-test'
      path: '/api/public/chat-test'
      fullPath: '/api/public/chat-test'
      preLoaderRoute: typeof ApiPublicChatTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag': {
      id: '/api/public/diag'
      path: '/api/public/diag'
      fullPath: '/api/public/diag'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-ingest': {
      id: '/api/public/market-ingest'
      path: '/api/public/market-ingest'
      fullPath: '/api/public/market-ingest'
      preLoaderRoute: typeof ApiPublicMarketIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBaseConhecimentoRoute: typeof AuthenticatedAdminBaseConhecimentoRoute
  AuthenticatedAdminCotacoesRoute: typeof AuthenticatedAdminCotacoesRoute
  AuthenticatedAdminIaRoute: typeof AuthenticatedAdminIaRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBaseConhecimentoRoute:
    AuthenticatedAdminBaseConhecimentoRoute,
  AuthenticatedAdminCotacoesRoute: AuthenticatedAdminCotacoesRoute,
  AuthenticatedAdminIaRoute: AuthenticatedAdminIaRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicChatTestRoute: ApiPublicChatTestRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
  ApiPublicMarketIngestRoute: ApiPublicMarketIngestRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
