/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMarketIngestRouteImport } from './routes/api/public/market-ingest'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/diag'
import { Route as ApiPublicChatTestRouteImport } from './routes/api/public/chat-test'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminCotacoesRouteImport } from './routes/_authenticated/admin.cotacoes'
import { Route as AuthenticatedAdminBaseConhecimentoRouteImport } from './routes/_authenticated/admin.base-conhecimento'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketIngestRoute = ApiPublicMarketIngestRouteImport.update({
  id: '/api/public/market-ingest',
  path: '/api/public/market-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/diag',
  path: '/api/public/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatTestRoute = ApiPublicChatTestRouteImport.update({
  id: '/api/public/chat-test',
  path: '/api/public/chat-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCotacoesRoute =
  AuthenticatedAdminCotacoesRouteImport.update({
    id: '/admin/cotacoes',
    path: '/admin/cotacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBaseConhecimentoRoute =
  AuthenticatedAdminBaseConhecimentoRouteImport.update({
    id: '/admin/base-conhecimento',
    path: '/admin/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/base-conhecimento': typeof AuthenticatedAdminBaseConhecimentoRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/api/public/chat-test': typeof ApiPublicChatTestRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/market-ingest': typeof ApiPublicMarketIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/base-conhecimento': typeof AuthenticatedAdminBaseConhecimentoRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/api/public/chat-test': typeof ApiPublicChatTestRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/market-ingest': typeof ApiPublicMarketIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/base-conhecimento': typeof AuthenticatedAdminBaseConhecimentoRoute
  '/_authenticated/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/api/public/chat-test': typeof ApiPublicChatTestRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/market-ingest': typeof ApiPublicMarketIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/base-conhecimento'
    | '/admin/cotacoes'
    | '/admin/produtos'
    | '/api/public/chat-test'
    | '/api/public/diag'
    | '/api/public/market-ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/base-conhecimento'
    | '/admin/cotacoes'
    | '/admin/produtos'
    | '/api/public/chat-test'
    | '/api/public/diag'
    | '/api/public/market-ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/base-conhecimento'
    | '/_authenticated/admin/cotacoes'
    | '/_authenticated/admin/produtos'
    | '/api/public/chat-test'
    | '/api/public/diag'
    | '/api/public/market-ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicChatTestRoute: typeof ApiPublicChatTestRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
  ApiPublicMarketIngestRoute: typeof ApiPublicMarketIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-ingest': {
      id: '/api/public/market-ingest'
      path: '/api/public/market-ingest'
      fullPath: '/api/public/market-ingest'
      preLoaderRoute: typeof ApiPublicMarketIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag': {
      id: '/api/public/diag'
      path: '/api/public/diag'
      fullPath: '/api/public/diag'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-test': {
      id: '/api/public/chat-test'
      path: '/api/public/chat-test'
      fullPath: '/api/public/chat-test'
      preLoaderRoute: typeof ApiPublicChatTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cotacoes': {
      id: '/_authenticated/admin/cotacoes'
      path: '/admin/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AuthenticatedAdminCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/base-conhecimento': {
      id: '/_authenticated/admin/base-conhecimento'
      path: '/admin/base-conhecimento'
      fullPath: '/admin/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedAdminBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBaseConhecimentoRoute: typeof AuthenticatedAdminBaseConhecimentoRoute
  AuthenticatedAdminCotacoesRoute: typeof AuthenticatedAdminCotacoesRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBaseConhecimentoRoute:
    AuthenticatedAdminBaseConhecimentoRoute,
  AuthenticatedAdminCotacoesRoute: AuthenticatedAdminCotacoesRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicChatTestRoute: ApiPublicChatTestRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
  ApiPublicMarketIngestRoute: ApiPublicMarketIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
